export type ShapeType = 'rect' | 'brackets' | 'arrow' | 'circle' | 'decision' | 'cloud' | 'person' | 'panel' | 'database' | 'database2' | 'firewall' | 'legend' | 'image' | 'plain-line' | 'line' | 'text' | 'frame' | 'group';
export type LegendIconType = Exclude<ShapeType, 'group' | 'legend' | 'frame'>;
export type LegendItem = {
    id: string;
    icon: LegendIconType;
    label: string;
    color: string;
    fill: string;
    borderStyle?: BorderStyle;
};
export type Point = {
    x: number;
    y: number;
};
export type View = {
    x: number;
    y: number;
    zoom: number;
};
export type Padding = {
    top: number;
    right: number;
    bottom: number;
    left: number;
};
export type AutoResizeAxis = 'both' | 'width' | 'height';
export type BorderStyle = 'solid' | 'dashed' | 'dotted' | 'double';
export type CornerStyle = 'rounded' | 'sharp';
export type ArrowDirection = 'none' | 'start' | 'end' | 'both';
export type RouteStyle = 'straight' | 'simple-orthogonal' | 'orthogonal' | 'curved';
export type TextAlign = 'left' | 'center' | 'right' | 'justify';
export type VerticalAlign = 'top' | 'middle' | 'bottom';
export type LabelSize = 'extra-small' | 'small' | 'medium' | 'large' | 'extra-large' | 'extra-extra-large';
export type IconCorner = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
export type ConnectorEndpoint = {
    type: 'free';
    x: number;
    y: number;
} | {
    type: 'shape';
    shapeId: string;
    position?: number;
};
export type CanvasShape = {
    id: string;
    type: ShapeType;
    name?: string;
    tags?: string[];
    x: number;
    y: number;
    width: number;
    height: number;
    rotation?: number;
    locked?: boolean;
    frameOrder?: number;
    frameFitContent?: boolean;
    parentId: string | null;
    color: string;
    label?: string;
    fill?: string;
    borderStyle?: BorderStyle;
    cornerStyle?: CornerStyle;
    strokeWidth?: number;
    labelColor?: string;
    labelAlign?: TextAlign;
    labelVerticalAlign?: VerticalAlign;
    labelSize?: LabelSize;
    labelBold?: boolean;
    labelItalic?: boolean;
    labelUnderline?: boolean;
    labelStrike?: boolean;
    labelWrap?: boolean;
    body?: string;
    bodyColor?: string;
    bodyAlign?: TextAlign;
    bodyVerticalAlign?: VerticalAlign;
    bodySize?: LabelSize;
    bodyBold?: boolean;
    bodyItalic?: boolean;
    bodyUnderline?: boolean;
    bodyStrike?: boolean;
    bodyWrap?: boolean;
    separatorColor?: string;
    separatorStyle?: BorderStyle;
    separatorWidth?: number;
    headerFill?: string;
    legendItems?: LegendItem[];
    imageData?: string;
    iconData?: string;
    iconCorner?: IconCorner;
    iconSize?: number;
    scaleTextWithBounds?: boolean;
    padding?: Padding;
    autoNest?: boolean;
    autoResize?: boolean;
    autoResizeAxis?: AutoResizeAxis;
    keepAspectRatio?: boolean;
    arrowDirection?: ArrowDirection;
    labelPosition?: number;
    labelRotation?: number;
    routeStyle?: RouteStyle;
    routePoints?: Point[];
    routeOffset?: number;
    lockAngle?: number;
    start?: ConnectorEndpoint;
    end?: ConnectorEndpoint;
};
export type CanvasState = {
    shapes: CanvasShape[];
    view: View;
    showGrid: boolean;
};
